# -*- coding: utf-8 -*-
"""build_event_SWI.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DpBNULF64pEUx_JMKF_uJqO-Wby0CUqf
"""

import pandas as pd
import numpy as np

# Monthly SWI grid
swi = pd.read_csv(
    "/content/sample_data/SWI_2000_2025.csv"
)

# Municipality-grid mapping
mapping = pd.read_parquet(
    "/content/sample_data/mapping_SWI_communes_weighted.parquet"
)

# CatNat database
df_catnat = pd.read_excel(
    "/content/sample_data/CatNat_secheresse_couvertes_clean.xlsx"
)

print(swi.shape)
print(mapping.shape)
print(df_catnat.shape)

print(swi.columns.tolist())
print(mapping.columns.tolist())
print(df_catnat.columns.tolist())

# ==========================================================
# 1. Harmonize variable names
# ==========================================================

swi = swi.rename(columns={
    "NUMERO": "grid_id",
    "SWI_UNIF_MENS": "swi"
})

# Data types
swi["grid_id"] = swi["grid_id"].astype(int)

mapping = mapping.rename(columns={
    "num_maille": "grid_id"
})

mapping["grid_id"] = mapping["grid_id"].astype(int)
mapping["code_insee"] = (
    mapping["code_insee"]
    .astype(str)
    .str.zfill(5)
)

# ==========================================================
# 2. Check dates
# ==========================================================

print(swi["DATE"].min())
print(swi["DATE"].max())

swi.head()

swi = swi.rename(columns={
    "NUMERO": "grid_id",
    "DATE": "month",
    "SWI_UNIF_MENS": "swi"
})

municipality_swi = swi.merge(
    mapping,
    on="grid_id",
    how="inner"
)

print(municipality_swi.shape)
municipality_swi.head()

municipality_swi["weighted_swi"] = (
    municipality_swi["swi"] *
    municipality_swi["weight"]
)

monthly_swi = (
    municipality_swi
    .groupby(
        ["code_insee", "month"],
        as_index=False
    )
    .agg(
        swi=("weighted_swi", "sum")
    )
)

print(monthly_swi.shape)
print(monthly_swi["code_insee"].nunique())
print(monthly_swi["month"].min())
print(monthly_swi["month"].max())

monthly_swi.head()

monthly_swi.to_parquet(
    "/content/SWI_monthly_communes_2000_2025.parquet",
    index=False,
    compression="snappy"
)

# ============================================================
# 3. Prepare CatNat events
# ============================================================

dfc = df_catnat.copy()

dfc["code_insee"] = (
    dfc["code_insee"]
    .astype(str)
    .str.zfill(5)
)

dfc["start_month"] = (
    pd.to_datetime(dfc["Début d'Evénement"])
      .values.astype("datetime64[M]")
)

dfc["end_month"] = (
    pd.to_datetime(dfc["Fin d'Evénement"])
      .values.astype("datetime64[M]")
)

dfc = dfc.reset_index(drop=True)
dfc["event_id"] = np.arange(len(dfc))

print(dfc.shape)
dfc.head()

# ============================================================
# 4. Expand events month by month
# ============================================================

def months_between(row):
    if pd.isna(row.start_month) or pd.isna(row.end_month):
        return []

    return pd.date_range(
        row.start_month,
        row.end_month,
        freq="MS"
    )


expanded = (
    dfc[["event_id", "code_insee", "start_month", "end_month"]]
    .assign(month=dfc.apply(months_between, axis=1))
    .explode("month", ignore_index=True)
    .dropna(subset=["month"])
)

print(expanded.shape)
expanded.head()

print(expanded["month"].dtype)
print(monthly_swi["month"].dtype)

monthly_swi["month"] = pd.to_datetime(
    monthly_swi["month"].astype(str),
    format="%Y%m"
)
print(monthly_swi["month"].dtype)

joined = expanded.merge(
    monthly_swi,
    on=["code_insee", "month"],
    how="left"
)

print(joined.shape)
joined.head()

# Minimum SWI par événement
idx = (
    joined.groupby("event_id")["swi"]
          .idxmin()
          .dropna()
          .astype(int)
)

swi_event = (
    joined.loc[idx, ["event_id", "swi", "month"]]
          .rename(columns={
              "swi": "swi_min",
              "month": "month_swi_min"
          })
          .set_index("event_id")
)

print(swi_event.shape)
swi_event.head()

print("Number of CatNat events:", len(dfc))
print("Number of events with SWI:", len(swi_event))
print("Number of events without SWI:", len(dfc) - len(swi_event))

final = (
    dfc.set_index("event_id")
       .join(swi_event, how="left")
       .reset_index(drop=True)
)
print(final["swi_min"].isna().mean())

final.loc[
    final["swi_min"].isna(),
    "Début d'Evénement"
].dt.year.value_counts().sort_index()

final.loc[
    final["swi_min"].isna() &
    (final["Début d'Evénement"].dt.year >= 2000),
    ["code_insee", "Nom_commune",
     "Début d'Evénement", "Fin d'Evénement"]
]

# ==========================================
# Base finale CatNat + SWI
# ==========================================

final = (
    dfc
    .set_index("event_id")
    .join(swi_event, how="left")
    .reset_index(drop=True)
)

print(final.shape)
final.head()

# Excel
final.to_excel(
    "/content/CatNat_drought_events_SWI.xlsx",
    index=False
)