# -*- coding: utf-8 -*-
"""merging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vmo816ALZNBCAjL7D6BvUHbDoNtAomGS
"""

import pandas as pd

# ==========================================================
# Load CatNat database
# ==========================================================

catnat = pd.read_excel(
    "/content/sample_data/base_complete.xlsx"
)

# ==========================================================
# Load event-level SWI database
# ==========================================================

swi = pd.read_excel(
    "/content/sample_data/CatNat_drought_events_SWI.xlsx"
)

print("CatNat database:", catnat.shape)
print("Event-level SWI database:", swi.shape)

print(catnat.duplicated().sum())
print(swi.duplicated().sum())

swi = swi[
    [
        "code_insee",
        "Début d'Evénement",
        "Fin d'Evénement",
        "swi_min"
    ]
].copy()

base = catnat.merge(
    swi,
    on=[
        "code_insee",
        "Début d'Evénement",
        "Fin d'Evénement"
    ],
    how="left"
)

print(catnat.shape)
print(swi.shape)

print(catnat["code_insee"].dtype)
print(swi["code_insee"].dtype)

print(catnat["Début d'Evénement"].dtype)
print(swi["Début d'Evénement"].dtype)

print(catnat["Fin d'Evénement"].dtype)
print(swi["Fin d'Evénement"].dtype)

print(base.shape)

print("Missing SWI:", base["swi_min"].isna().sum())

print(
    base.loc[
        base["swi_min"].isna(),
        "Début d'Evénement"
    ].dt.year.value_counts().sort_index()
)

print(base.shape)
print(base["swi_min"].isna().mean())

base.loc[
    base["swi_min"].isna(),
    "Début d'Evénement"
].dt.year.value_counts().sort_index()

# Conserver uniquement les événements à partir de 2000
base = base[
    base["Début d'Evénement"].dt.year >= 2000
].copy()

print(base.shape)
print(base["swi_min"].isna().mean())

print(
    base["Début d'Evénement"]
    .dt.year
    .value_counts()
    .sort_index()
)

# Renommer RGA en CSS
base = base.rename(columns={
    "RGA": "CSS"
})

# Réordonner les colonnes
base = base[
    [
        "code_insee",
        "Nom_commune",
        "Début d'Evénement",
        "Fin d'Evénement",
        "Nom du péril",
        "decision",
        "nb_decisions",
        "CDD",
        "spi_min",
        "spei_min",
        "swi_min",
        "CSS",
        "n_dwellings",
        "old_housing_share",
    ]
]

base.head()

base = base.rename(columns={

    "Nom_commune": "municipality",

    "Début d'Evénement": "event_start",

    "Fin d'Evénement": "event_end",

    "Nom du péril": "hazard",

    "RGA": "CSS",

    "spi_min": "SPI",

    "spei_min": "SPEI",

    "swi_min": "SWI"

})

base = base[[
    "code_insee",
    "municipality",
    "event_start",
    "event_end",
    "hazard",
    "decision",
    "nb_decisions",
    "CDD",
    "SPI",
    "SPEI",
    "SWI",
    "CSS",
    "n_dwellings",
    "old_housing_share"
]]

# Sauvegarde Excel
base.to_excel(
    "/content/final_data_climat_CSS_SWI.xlsx",
    index=False
)

# ==========================================================
# Descriptive statistics
# ==========================================================

print("Dataset shape:", base.shape)

print("\nColumns:")
print(base.columns.tolist())

print("\nVariable types:")
print(base.dtypes)

print("\nMissing values:")
display(base.isna().sum().to_frame("Missing values"))

print("\nSummary statistics (numeric variables):")
display(base.describe().T)

print("\nNumber of municipalities:", base["code_insee"].nunique())

print("Number of events:", len(base))

print("Decision distribution:")
display(base["decision"].value_counts().sort_index())

print("Hazard distribution:")
display(base["hazard"].value_counts())

print("Study period:")
print("Start:", base["event_start"].min())
print("End  :", base["event_end"].max())