# -*- coding: utf-8 -*-
"""Mergingriskvariables_Review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LA_dQ9KKxBr1QLbZGcPT5gHo9Uc1DAMO
"""

import pandas as pd
import numpy as np

################################### upload Data
spi = pd.read_excel("/content/sample_data/CatNat_drought_SPI_min_3_6_12.xlsx")

print(spi.columns.tolist())

spei=pd.read_excel("/content/sample_data/CatNat_drought_SPEI_min_3_6_12.xlsx")
print(spei.columns.tolist())

cdd = pd.read_excel("/content/sample_data/CatNat_drought_events_CDD.xlsx")
print(cdd.columns.tolist())

swi = pd.read_excel("/content/sample_data/CatNat_drought_events_SWI.xlsx")
print(swi.columns.tolist())

print(final.columns.tolist())

import pandas as pd

# ============================================================
# Load files
# ============================================================

spi  = pd.read_excel("/content/sample_data/CatNat_drought_SPI_min_3_6_12.xlsx")
spei = pd.read_excel("/content/sample_data/CatNat_drought_SPEI_min_3_6_12.xlsx")
cdd  = pd.read_excel("/content/sample_data/CatNat_drought_events_CDD.xlsx")
swi  = pd.read_excel("/content/sample_data/CatNat_drought_events_SWI.xlsx")

# ============================================================
# Standardize keys
# ============================================================

dfs = [spi, spei, cdd, swi]

for df in dfs:
    df["code_insee"] = df["code_insee"].astype(str).str.zfill(5)
    df["Début d'Evénement"] = pd.to_datetime(df["Début d'Evénement"])
    df["Fin d'Evénement"] = pd.to_datetime(df["Fin d'Evénement"])

key = [
    "code_insee",
    "Début d'Evénement",
    "Fin d'Evénement"
]

# ============================================================
# Base table
# ============================================================

final = spi[
    [
        "code_insee",
        "Nom_commune",
        "Début d'Evénement",
        "Fin d'Evénement",
        "Nom du péril",
        "decision",
        "nb_decisions",
        "spi_min",
    ]
].copy()

# ============================================================
# Merge remaining indicators
# ============================================================

final = (
    final
    .merge(
        spei[key + ["spei_min"]],
        on=key,
        how="left"
    )
    .merge(
        cdd[key + ["CDDmax_event"]],
        on=key,
        how="left"
    )
    .merge(
        swi[key + ["swi_min"]],
        on=key,
        how="left"
    )
)

# ============================================================
# Final column order
# ============================================================

final = final[
    [
        "code_insee",
        "Nom_commune",
        "Début d'Evénement",
        "Fin d'Evénement",
        "Nom du péril",
        "decision",
        "nb_decisions",
        "swi_min",
        "CDDmax_event",
        "spi_min",
        "spei_min"
    ]
]

# ============================================================
# Checks
# ============================================================

print(final.shape)
print("Duplicated events :", final.duplicated(key).sum())

print("\nMissing values")
print(final.isna().sum())

# ============================================================
# Export
# ============================================================

final.to_excel(
    "/content/CatNat_drought_final_database.xlsx",
    index=False
)

final.to_parquet(
    "/content/CatNat_drought_final_database.parquet",
    index=False,
    compression="snappy"
)

print("\n✔ Final database exported.")

missing = final[final["swi_min"].isna()]

print(missing["Début d'Evénement"].dt.year.value_counts().sort_index())