# -*- coding: utf-8 -*-
"""Reconigtion_analyse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FnXG-4MHmPEaje6dFpyYzB8Lq851RXCr
"""

import pandas as pd

# ==========================================================
# Load CatNat database
# ==========================================================

catnat = pd.read_excel(
    "/content/sample_data/base_complete.xlsx"
)

catnat

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

# Date
catnat["Début d'Evénement"] = pd.to_datetime(catnat["Début d'Evénement"])

# Année
catnat["year"] = catnat["Début d'Evénement"].dt.year

# Taux annuel de reconnaissance
annual = (
    catnat
    .groupby("year", as_index=False)["decision"]
    .mean()
)

annual["recognition_rate"] = annual["decision"] * 100

annual = annual.drop(columns="decision")

annual.head()

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
from statsmodels.nonparametric.smoothers_lowess import lowess

!pip install ruptures



import ruptures as rpt
import numpy as np
signal = annual["recognition_rate"].values
years = annual["year"].values

import ruptures as rpt

signal = annual["recognition_rate"].values
years = annual["year"].values

algo = rpt.Binseg(model="l2").fit(signal)

breaks = algo.predict(n_bkps=1)

print(breaks)

break_year = years[breaks[0]-1]
print("Estimated break year:", break_year)

import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
from statsmodels.nonparametric.smoothers_lowess import lowess

# ==========================================================
# 1. Configuration du Style Journal Académique (Ex: Times New Roman)
# ==========================================================
plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['Times New Roman', 'DejaVu Serif', 'Liberation Serif']
plt.rcParams['axes.edgecolor'] = '#333333'
plt.rcParams['axes.linewidth'] = 0.8

# LOWESS (calcul inchangé)
smooth = lowess(
    annual["recognition_rate"],
    annual["year"],
    frac=0.60,
    return_sorted=True
)

# Figure haute définition (600 DPI)
fig, ax = plt.subplots(figsize=(9, 4.5), dpi=600)

# ==========================================================
# 2. Éléments Graphiques
# ==========================================================

# Tracé de la tendance LOWESS (Bleu académique profond)
ax.plot(
    smooth[:, 0],
    smooth[:, 1],
    lw=2.5,
    color="#0B4F71",
    zorder=3,
    label="LOWESS trend (frac=0.60)"
)

# Ligne de rupture structurelle (Rouge brique élégant)
ax.axvline(
    2002,
    color="#A61C1C",
    lw=1.5,
    ls="--",
    zorder=2
)

# Points de données (Noir-gris avec contour blanc pour un contraste maximal)
ax.scatter(
    annual.year,
    annual.recognition_rate,
    s=35,
    color="#1A1A1A",
    edgecolor="white",
    linewidth=0.6,
    zorder=4,
    label="Observed annual rate"
)

# ==========================================================
# 3. Annotation Professionnelle avec Flèche
# ==========================================================
ax.annotate(
    "Structural break\n(2002)",
    xy=(2002, 25),          # Point pointé par la flèche
    xytext=(2005.5, 18),     # Position du texte (ajustable si besoin)
    color="#A61C1C",
    fontsize=9.5,
    fontweight="bold",
    arrowprops=dict(
        arrowstyle="->",
        color="#A61C1C",
        lw=0.8,
        connectionstyle="arc3,rad=-0.1" # Légère courbe élégante de la flèche
    ),
    zorder=5
)

# ==========================================================
# 4. Axes et Formats
# ==========================================================
ax.set_xlim(1988, 2023.5)
ax.set_ylim(0, 105)

ax.set_xlabel("Year", fontsize=11, labelpad=8)
ax.set_ylabel("Recognition Rate (%)", fontsize=11, labelpad=8)

# Formatage de l'axe des ordonnées (ex: 20% au lieu de 20.0%)
ax.yaxis.set_major_formatter(mtick.PercentFormatter(decimals=0))

# ==========================================================
# 5. Habillage Épuré
# ==========================================================
ax.grid(
    axis="y",
    alpha=0.4,
    color="#D3D3D3",
    linestyle=":"
)

# Suppression des bordures supérieures et droites (style épuré)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# Configuration fine des ticks
ax.tick_params(axis='both', which='major', labelsize=10, colors='#333333')

# Légende discrète en bas à gauche
ax.legend(loc="lower left", frameon=True, facecolor="white", edgecolor="none", fontsize=9)

# Sauvegarde et affichage
plt.tight_layout()
plt.savefig(
    "Recognition_Regime.png",
    dpi=600,
    bbox_inches="tight"
)
plt.show()

import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import numpy as np
import statsmodels.api as sm  # Used to compute regression confidence intervals

# ==========================================================
# Academic Style Customization
# ==========================================================
plt.rcParams["font.family"] = "serif"
plt.rcParams["font.serif"] = ["Times New Roman", "DejaVu Serif"]
plt.rcParams["axes.edgecolor"] = "#222222"
plt.rcParams["axes.linewidth"] = 0.6
plt.rcParams["xtick.major.width"] = 0.6
plt.rcParams["ytick.major.width"] = 0.6

# "Top Journal" color palette
COLOR_OBS = "#2D3748"       # Elegant slate gray
COLOR_TREND = "#1A365D"     # Institutional navy blue
COLOR_BREAK = "#8C1D40"     # Academic burgundy
COLOR_SHADE = "#1A365D"     # Base color for confidence band

# ==========================================================
# Data Processing & Segmented Regressions
# ==========================================================
before = annual[annual["year"] <= 2002].copy()
after  = annual[annual["year"] >= 2002].copy()

def get_predictions_and_ci(df):
    """Computes fitted values and 95% confidence intervals."""
    X = sm.add_constant(df["year"])
    model = sm.OLS(df["recognition_rate"], X).fit()
    predictions = model.get_prediction(X)
    summary = predictions.summary_frame(alpha=0.05)
    return df["year"], summary["mean"], summary["mean_ci_lower"], summary["mean_ci_upper"]

x_bef, y_bef, ci_low_bef, ci_upp_bef = get_predictions_and_ci(before)
x_aft, y_aft, ci_low_aft, ci_upp_aft = get_predictions_and_ci(after)

# ==========================================================
# Figure Layout
# ==========================================================
fig, ax = plt.subplots(figsize=(8.5, 4.8), dpi=600)

# 1. Confidence intervals (drawn first to remain in the background)
ax.fill_between(
    x_bef,
    ci_low_bef,
    ci_upp_bef,
    color=COLOR_SHADE,
    alpha=0.08,
    label="95% Confidence interval"
)

ax.fill_between(
    x_aft,
    ci_low_aft,
    ci_upp_aft,
    color=COLOR_SHADE,
    alpha=0.08
)

# 2. Structural breakpoint
ax.axvline(
    2002,
    color=COLOR_BREAK,
    linestyle="--",
    linewidth=1.1,
    zorder=1
)

# 3. Segmented linear trends
ax.plot(
    x_bef,
    y_bef,
    color=COLOR_TREND,
    lw=2.0,
    zorder=2,
    label="Segmented linear trend"
)

ax.plot(
    x_aft,
    y_aft,
    color=COLOR_TREND,
    lw=2.0,
    zorder=2
)

# 4. Observed annual recognition rates
ax.scatter(
    annual["year"],
    annual["recognition_rate"],
    s=28,
    color=COLOR_OBS,
    edgecolor="#FFFFFF",
    linewidth=0.6,
    zorder=3,
    alpha=0.9,
    label="Observed annual rate"
)

# ==========================================================
# Annotation
# ==========================================================
ax.text(
    2002.5,
    85,
    "Structural Break\n(2002)",
    color=COLOR_BREAK,
    fontsize=9.5,
    fontfamily="serif",
    style="italic",
    linespacing=1.2
)

# ==========================================================
# Axes, Labels & Grid
# ==========================================================
ax.set_xlim(1987.5, 2023.5)
ax.set_ylim(0, 105)

ax.set_xlabel("Year", fontsize=10.5, labelpad=8)
ax.set_ylabel("Recognition Rate (%)", fontsize=10.5, labelpad=8)

# Axis formatting
ax.yaxis.set_major_formatter(mtick.PercentFormatter(decimals=0))
ax.xaxis.set_major_locator(plt.MaxNLocator(integer=True))

# Clean spines
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.spines["left"].set_color("#718096")
ax.spines["bottom"].set_color("#718096")

# Horizontal grid only
ax.grid(
    axis="y",
    linestyle="-",
    color="#E2E8F0",
    linewidth=0.5,
    zorder=0
)

# Clean legend (Observed → Trend → Confidence interval)
handles, labels = ax.get_legend_handles_labels()
order = [2, 1, 0]

ax.legend(
    [handles[idx] for idx in order],
    [labels[idx] for idx in order],
    frameon=False,
    loc="lower left",
    fontsize=9,
    bbox_to_anchor=(0.01, 0.02)
)

# ==========================================================
# Save Figure
# ==========================================================
plt.tight_layout()

plt.savefig(
    "Recognition_Rate_evoltion.pdf",
    bbox_inches="tight"
)

plt.savefig(
    "Recognition_Rate_evolution.png",
    dpi=600,
    bbox_inches="tight"
)

plt.show()