# -*- coding: utf-8 -*-
"""safaran_mappingreview.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zyBV3XvAa9fCUHivGoikvNFGyEwWi5-S
"""

import pandas as pd
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.geometry import box
FILE_GRILLE_TERRESTRE = "/content/sample_data/grilleSafran_ut1.xls"

df_grid = pd.read_excel(FILE_GRILLE_TERRESTRE)
df_grid

from shapely.geometry import box
import geopandas as gpd

half = 4000

poly = box(
    df_grid.loc[0, "x"] - half,
    df_grid.loc[0, "y"] - half,
    df_grid.loc[0, "x"] + half,
    df_grid.loc[0, "y"] + half,
)

gdf = gpd.GeoDataFrame(
    geometry=[poly],
    crs="EPSG:27572"
)

print(poly.bounds)

from shapely.geometry import box
import geopandas as gpd

# ============================================================
# Build the SAFRAN grid (8 km × 8 km)
# ============================================================

half = 4000

gdf_grid = df_grid.copy()

gdf_grid["geometry"] = gdf_grid.apply(
    lambda r: box(
        r["x"] - half,
        r["y"] - half,
        r["x"] + half,
        r["y"] + half
    ),
    axis=1
)

gdf_grid = gpd.GeoDataFrame(
    gdf_grid,
    geometry="geometry",
    crs="EPSG:27572"
)

print(gdf_grid.shape)
print(gdf_grid.crs)

gdf_grid.head()

# ============================================================
# Load municipality boundaries
# ============================================================

communes = gpd.read_file(
    "/content/sample_data/communes_simplified.gpkg",
    layer="communes"
)

communes["code_insee"] = (
    communes["code_insee"]
    .astype(str)
    .str.zfill(5)
)

# Metropolitan France only
communes = communes[
    ~communes["code_insee"].str.startswith(("97", "98"))
].copy()

print(communes.shape)
print(communes.crs)

# Project to Lambert II Extended (EPSG:27572)
communes = communes.to_crs("EPSG:27572")

print(communes.crs)

print("Communes :", communes.total_bounds)
print("SAFRAN   :", gdf_grid.total_bounds)

intersections = gpd.overlay(
    communes,
    gdf_grid,
    how="intersection",
    keep_geom_type=True
)

print(intersections["code_insee"].nunique())

# ============================================================
# Municipality–SAFRAN grid intersections
# ============================================================

intersections = gpd.overlay(
    communes,
    gdf_grid,
    how="intersection",
    keep_geom_type=True
)

print("Intersections :", intersections.shape)
print("Communities covered :", intersections["code_insee"].nunique())

# ============================================================
# Municipalities without grid intersection
# ============================================================

missing_codes = sorted(
    set(communes["code_insee"]) -
    set(intersections["code_insee"])
)

print(f"Municipalities without intersection: {len(missing_codes)}")

if len(missing_codes) > 0:

    communes_missing = communes[
        communes["code_insee"].isin(missing_codes)
    ].copy()

    print("Searching nearest grid cell...")

    nearest = gpd.sjoin_nearest(
        communes_missing,
        gdf_grid,
        how="left",
        distance_col="distance_m"
    )

    nearest["weight"] = 1.0

    nearest["area_intersection"] = nearest.geometry.area

    print(nearest[["code_insee", "x", "y", "distance_m"]].head())

else:

    nearest = gpd.GeoDataFrame(columns=intersections.columns)

print(
    f"Fallback applied to {len(nearest)} municipalities."
)

print(intersections.columns.tolist())
print()
print(nearest.columns.tolist())

nearest = nearest[
    [
        "code_insee",
        "nom_officiel",
        "x",
        "y",
        "lon",
        "lat",
        "geometry"
    ]
].copy()

nearest["fallback"] = True
intersections["fallback"] = False

# ============================================================
# Build final municipality–grid mapping
# ============================================================

intersections = intersections.copy()
nearest = nearest.copy()

for col in ["fallback", "weight", "area_intersection", "area_commune"]:
    if col in intersections.columns:
        intersections = intersections.drop(columns=[col])
    if col in nearest.columns:
        nearest = nearest.drop(columns=[col])

# Common columns
base_cols = [
    "code_insee",
    "nom_officiel",
    "x",
    "y",
    "lon",
    "lat",
    "geometry"
]

intersections_clean = intersections[base_cols].copy()
nearest_clean = nearest[base_cols].copy()

intersections_clean["fallback"] = False
nearest_clean["fallback"] = True

mapping = pd.concat(
    [intersections_clean, nearest_clean],
    ignore_index=True
)

print("Number of rows:", len(mapping))
print("Number of municipalities:", mapping["code_insee"].nunique())
print("Fallback assignments:", mapping["fallback"].sum())

# ============================================================
# Municipality areas
# ============================================================

communes_area = communes[
    ["code_insee", "geometry"]
].copy()

communes_area["area_commune"] = communes_area.geometry.area

communes_area = communes_area[
    ["code_insee", "area_commune"]
]

mapping = mapping.merge(
    communes_area,
    on="code_insee",
    how="left"
)

# ============================================================
# Intersection areas and weights
# ============================================================

mapping["area_intersection"] = mapping.geometry.area

mapping["weight"] = (
    mapping["area_intersection"]
    /
    mapping["area_commune"]
)

# Fallback municipalities receive full weight
mapping.loc[
    mapping["fallback"],
    "area_intersection"
] = mapping.loc[
    mapping["fallback"],
    "area_commune"
]

mapping.loc[
    mapping["fallback"],
    "weight"
] = 1.0

# ============================================================
# Normalize weights
# ============================================================

mapping["coverage"] = (
    mapping
    .groupby("code_insee")["weight"]
    .transform("sum")
)

mapping["weight"] = (
    mapping["weight"]
    /
    mapping["coverage"]
)

# ============================================================
# Validation
# ============================================================

coverage = (
    mapping
    .groupby("code_insee")["weight"]
    .sum()
)

print("\nWeight summary:")
print(coverage.describe())

print(
    "\nMunicipalities with weight sum different from 1:",
    (~np.isclose(coverage, 1.0, atol=1e-8)).sum()
)

print(
    "Fallback municipalities:",
    mapping["fallback"].sum()
)

mapping_final = (
    mapping[["code_insee", "x", "y", "weight"]]
    .sort_values(["code_insee", "x", "y"])
    .reset_index(drop=True)
)

mapping_final.to_csv(
    "/content/mapping_SAFRAN_communes_weighted.csv",
    index=False
)

mapping_final.to_parquet(
    "/content/mapping_SAFRAN_communes_weighted.parquet",
    index=False
)

print(mapping_final.shape)
print(mapping_final["code_insee"].nunique())

coverage = mapping.groupby("code_insee")["weight"].sum()

print(coverage.describe())

print(
    "Communes dont la somme des poids ≠ 1 :",
    (~np.isclose(coverage, 1.0, atol=1e-10)).sum()
)

print("Nombre de communes :", mapping_final["code_insee"].nunique())
print("Nombre de couples commune-maille :", len(mapping_final))
print("Nombre moyen de mailles par commune :",
      mapping_final.groupby("code_insee").size().mean())

print("Maximum :", mapping_final.groupby("code_insee").size().max())
print("Fallback :", mapping["fallback"].sum())

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# ==========================================================
# FILES
# ==========================================================

MAPPING = "/content/mapping_SAFRAN_communes_weighted.parquet"

COMMUNES = "/content/sample_data/communes_simplified.gpkg"
LAYER = "communes"

# ==========================================================
# LOAD COMMUNES
# ==========================================================

gdf = gpd.read_file(COMMUNES, layer=LAYER)

gdf["code_insee"] = (
    gdf["code_insee"]
    .astype(str)
    .str.zfill(5)
)

# Metropolitan France only
gdf = gdf[
    ~gdf["code_insee"].str.startswith(("97","98"))
].copy()

gdf = gdf.to_crs("EPSG:2154")

# ==========================================================
# LOAD MAPPING
# ==========================================================

mapping = pd.read_parquet(MAPPING)

# ==========================================================
# NUMBER OF SAFRAN CELLS PER MUNICIPALITY
# ==========================================================

n_cells = (
    mapping
    .groupby("code_insee")
    .size()
    .rename("n_cells")
)

gdf = gdf.merge(
    n_cells,
    on="code_insee",
    how="left"
)

gdf["n_cells"] = gdf["n_cells"].fillna(0).astype(int)

# ==========================================================
# CLASSES
# ==========================================================

def classify(x):

    if x == 1:
        return "1"

    elif x == 2:
        return "2"

    elif x == 3:
        return "3"

    else:
        return "≥4"

gdf["class"] = gdf["n_cells"].apply(classify)

# ==========================================================
# COLORS
# ==========================================================

colors = {
    "1":"#1B7837",
    "2":"#FDB863",
    "3":"#E66101",
    "≥4":"#B2182B"
}

# ==========================================================
# PLOT
# ==========================================================

plt.rcParams["font.family"] = "serif"

fig, ax = plt.subplots(
    figsize=(8.5,10),
    dpi=600
)

# draw municipalities

for c in ["1","2","3","≥4"]:

    gdf[
        gdf["class"]==c
    ].plot(
        ax=ax,
        color=colors[c],
        linewidth=0
    )

# municipal boundaries

gdf.boundary.plot(
    ax=ax,
    linewidth=0.03,
    edgecolor="white"
)

ax.set_axis_off()

# ==========================================================
# LEGEND
# ==========================================================

handles = [
    mpatches.Patch(color=colors["1"],label="1 SAFRAN cell"),
    mpatches.Patch(color=colors["2"],label="2 SAFRAN cells"),
    mpatches.Patch(color=colors["3"],label="3 SAFRAN cells"),
    mpatches.Patch(color=colors["≥4"],label="≥4 SAFRAN cells")
]

ax.legend(
    handles=handles,
    title="Number of intersecting\nSAFRAN cells",
    loc="lower left",
    frameon=False,
    fontsize=9,
    title_fontsize=10
)

plt.title(
    "Surface-weighted municipality–SAFRAN mapping",
    fontsize=15,
    fontweight="bold"
)

plt.tight_layout()

plt.savefig(
    "/content/Figure_SurfaceWeightedMapping.png",
    dpi=600,
    bbox_inches="tight"
)

plt.show()

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

# ==========================================================
# 1. PATHS AND CONFIGURATION
# ==========================================================
MAPPING = "/content/mapping_SAFRAN_communes_weighted.parquet"
COMMUNES = "/content/sample_data/communes_simplified.gpkg"
LAYER = "communes"

# ==========================================================
# 2. LOAD & CLEAN DATA
# ==========================================================
gdf = gpd.read_file(COMMUNES, layer=LAYER)

gdf["code_insee"] = (
    gdf["code_insee"]
    .astype(str)
    .str.zfill(5)
)

# Metropolitan France only
gdf = gdf[
    ~gdf["code_insee"].str.startswith(("97", "98"))
].copy()

gdf = gdf.to_crs("EPSG:2154")

mapping = pd.read_parquet(MAPPING)

# ==========================================================
# 3. DATA PROCESSING & CLASSIFICATION
# ==========================================================
n_cells = (
    mapping
    .groupby("code_insee")
    .size()
    .rename("n_cells")
)

gdf = gdf.merge(
    n_cells,
    on="code_insee",
    how="left"
)

gdf["n_cells"] = gdf["n_cells"].fillna(0).astype(int)

# Categorical classification for strict legend ordering
def classify(x):
    if x == 1:   return "1"
    elif x == 2: return "2"
    elif x == 3: return "3"
    else:        return "≥4"

gdf["class"] = gdf["n_cells"].apply(classify)
category_order = ["1", "2", "3", "≥4"]
gdf["class"] = pd.Categorical(gdf["class"], categories=category_order, ordered=True)

# Global statistics
mean_cells = gdf["n_cells"].mean()
median_cells = gdf["n_cells"].median()
maximum = gdf["n_cells"].max()

# ==========================================================
# 4. GRAPHICAL SETUP & DRAWING
# ==========================================================
plt.rcParams["font.family"] = "serif"
plt.rcParams['font.serif'] = ['Times New Roman', 'DejaVu Serif', 'Liberation Serif']

fig, ax = plt.subplots(figsize=(9, 10), dpi=600)

# Academic Color Palette
color_list = ["#2166AC", "#92C5DE", "#F4A261", "#C1121F"]
custom_cmap = ListedColormap(color_list)

# Main Plot: Categories with built-in clean white borders
gdf.plot(
    column="class",
    cmap=custom_cmap,
    edgecolor="#FFFFFF",
    linewidth=0.08,
    ax=ax,
    legend=True,
    legend_kwds={
        "title": "Number of\nSAFRAN cells",
        "loc": "lower left",
        "bbox_to_anchor": (0.02, 0.16),  # Moved up to clear space below
        "frameon": False,
        "fontsize": 10.5,
        "title_fontsize": 11.5
    }
)

ax.set_axis_off()

# Title
ax.set_title(
    "Surface-Weighted Municipality–SAFRAN Mapping",
    fontsize=16,
    fontweight="bold",
    pad=15
)

# ==========================================================
# 5. SUMMARY STATISTICS BOX (Stacked beneath the legend)
# ==========================================================
stats_text = (
    f"Total Municipalities: {len(gdf):,}\n"
    f"Mean cells/municipality: {mean_cells:.2f}\n"
    f"Median: {median_cells:.0f}\n"
    f"Maximum: {maximum}"
)

# Placed at the very bottom-left corner (Y=0.02), completely freeing the Corsican area
ax.text(
    0.02, 0.02,
    stats_text,
    transform=ax.transAxes,
    ha="left",
    va="bottom",
    fontsize=9.5,
    color="#2C3E50",
    linespacing=1.4,
    bbox=dict(
        facecolor="#F8F9F9",
        edgecolor="#BDC3C7",
        boxstyle="square,pad=0.5",
        linewidth=0.5
    )
)

# ==========================================================
# 6. EXPORT
# ==========================================================
plt.tight_layout()

plt.savefig(
    "/content/Figure_SurfaceWeightedMapping_Final.png",
    dpi=600,
    bbox_inches="tight",
    facecolor="white"
)

plt.show()

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib as mpl

# ==========================================================
# FILES
# ==========================================================

MAPPING = "/content/mapping_SAFRAN_communes_weighted.parquet"

COMMUNES = "/content/sample_data/communes_simplified.gpkg"
LAYER = "communes"

OUTPUT = "/content/Figure_DominantWeight_SAFRAN.png"

# ==========================================================
# LOAD MUNICIPALITIES
# ==========================================================

gdf = gpd.read_file(COMMUNES, layer=LAYER)

gdf["code_insee"] = (
    gdf["code_insee"]
    .astype(str)
    .str.zfill(5)
)

gdf = gdf[
    ~gdf["code_insee"].str.startswith(("97", "98"))
].copy()

gdf = gdf.to_crs("EPSG:2154")

# ==========================================================
# LOAD MAPPING
# ==========================================================

mapping = pd.read_parquet(MAPPING)

mapping["code_insee"] = (
    mapping["code_insee"]
    .astype(str)
    .str.zfill(5)
)

dominant = (
    mapping
    .groupby("code_insee")["weight"]
    .max()
    .rename("dominant_weight")
)

gdf = gdf.merge(
    dominant,
    on="code_insee",
    how="left"
)

# ==========================================================
# QUANTILE CLASSES
# ==========================================================

gdf["weight_class"] = pd.qcut(
    gdf["dominant_weight"],
    q=5,
    duplicates="drop"
)

# ==========================================================
# STYLE
# ==========================================================

plt.rcParams.update({
    "font.family":"serif",
    "font.serif":[
        "Times New Roman",
        "DejaVu Serif"
    ]
})

fig, ax = plt.subplots(
    figsize=(8.2,9.3),
    dpi=600
)

# ==========================================================
# MAP
# ==========================================================

gdf.plot(
    column="weight_class",
    cmap="YlOrRd",
    linewidth=0,
    edgecolor="none",
    categorical=True,
    legend=True,
    legend_kwds={
        "title":"Dominant weight",
        "loc":"lower left",
        "frameon":False,
        "fontsize":10,
        "title_fontsize":11
    },
    ax=ax
)

# ==========================================================
# OUTLINE
# ==========================================================

gdf.dissolve().boundary.plot(
    ax=ax,
    color="#4D4D4D",
    linewidth=0.45
)

# ==========================================================
# TITLE
# ==========================================================

#ax.set_title(
    #"Largest Surface Weight Assigned to a SAFRAN Grid Cell",
   # fontsize=15,
    #fontweight="bold",
   # pad=12
#)

ax.set_axis_off()

# ==========================================================
# IMPROVE LEGEND LABELS
# ==========================================================

leg = ax.get_legend()

labels = []

quantiles = gdf["dominant_weight"].quantile(
    [0,0.2,0.4,0.6,0.8,1]
).round(2)

for i in range(5):
    labels.append(
        f"{quantiles.iloc[i]:.2f} – {quantiles.iloc[i+1]:.2f}"
    )

for txt,label in zip(leg.get_texts(),labels):
    txt.set_text(label)

# ==========================================================
# EXPORT
# ==========================================================

plt.tight_layout()

plt.savefig(
    OUTPUT,
    dpi=600,
    bbox_inches="tight",
    facecolor="white"
)

plt.show()

print(gdf["weight_class"].value_counts())
print(gdf["weight_class"].cat.categories)