# -*- coding: utf-8 -*-
"""swi_mappingreview.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ESXBOL7a-qmEM-y7bO-Umarh3rAAcJG6
"""

import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import box
import matplotlib.pyplot as plt

# ============================================================
# 1. Load SWI datasets
# ============================================================

swi1 = pd.read_csv(
    "/content/sample_data/swi.200001-200912.csv.gz",
    sep=";"
)

swi2 = pd.read_csv(
    "/content/sample_data/swi.201001-201912.csv.gz",
    sep=";"
)

swi3 = pd.read_csv(
    "/content/sample_data/swi.202001-202512.csv.gz",
    sep=";"
)

# Merge SWI datasets
swi = pd.concat(
    [swi1, swi2, swi3],
    ignore_index=True
)

print("SWI dataset shape:", swi.shape)
print("Time period:", swi["DATE"].min(), "→", swi["DATE"].max())
print("Number of SWI grid cells:", swi["NUMERO"].nunique())
print("Number of time steps:", swi["DATE"].nunique())

display(swi.head())

swi.info()
display(swi.describe())

print("Missing values:")
print(swi.isna().sum())

duplicates = swi.duplicated(
    subset=["NUMERO", "DATE"]
).sum()

print("Duplicate NUMERO-DATE pairs:", duplicates)

assert duplicates == 0, (
    "Duplicate NUMERO-DATE pairs found in the SWI dataset."
)

swi.to_csv(
    "/content/SWI_2000_2025.csv",
    index=False
)

print("Merged SWI dataset saved.")

# ============================================================
# 3. Load the reference SAFRAN municipality mapping
# ============================================================

mapping = pd.read_csv(
    "/content/sample_data/mapping_8602_communes.csv",
    sep=";"
)

print("Reference mapping shape:", mapping.shape)

display(mapping.head())

# ============================================================
# 4. Check SWI grid coordinates
# ============================================================

coords_swi = (
    swi[["NUMERO", "LAMBX", "LAMBY"]]
    .drop_duplicates()
)

print("Number of unique SWI grid cells:", swi["NUMERO"].nunique())
print("Number of unique NUMERO-LAMBX-LAMBY combinations:", coords_swi.shape[0])

display(coords_swi.head(20))

assert (
    coords_swi.shape[0] == swi["NUMERO"].nunique()
), "Some SWI grid cell IDs are associated with multiple coordinate pairs."

# ============================================================
# 5. Load SWI grid metadata
# ============================================================

mailles = pd.read_csv(
    "/content/sample_data/modeles-caracteristiques-geographiques-mailles-swi-20260316.csv",
    sep=";",
    skiprows=5,
    names=[
        "num_maille",
        "lambx",
        "lamby",
        "lambx93",
        "lamby93",
        "lat_dg",
        "lon_dg"
    ]
)

print("SWI grid metadata shape:", mailles.shape)
print("Columns:", mailles.columns.tolist())

display(mailles.head())

print("Total number of grid cells:", len(mailles))
print("Number of unique grid cell IDs:", mailles["num_maille"].nunique())

assert (
    len(mailles) == mailles["num_maille"].nunique()
), "Duplicate grid cell IDs found in the SWI grid metadata."

# ============================================================
# 6. Check consistency between SWI and grid metadata
# ============================================================

missing = sorted(
    set(swi["NUMERO"].unique()) -
    set(mailles["num_maille"].unique())
)

extra = sorted(
    set(mailles["num_maille"].unique()) -
    set(swi["NUMERO"].unique())
)

print("SWI grid cells missing from the metadata file:", len(missing))
print("Missing grid cells:", missing)

print("Grid cells present in the metadata but absent from the SWI dataset:", len(extra))
print("Additional grid cells:", extra)

# Inspect missing grid cells
if len(missing) > 0:

    print("\nDetails of missing grid cells:")

    display(
        swi.loc[
            swi["NUMERO"].isin(missing),
            ["NUMERO", "LAMBX", "LAMBY", "DATE"]
        ]
        .drop_duplicates()
        .sort_values("NUMERO")
    )

# Inspect additional grid cells
if len(extra) > 0:

    print("\nDetails of additional grid cells:")

    display(
        mailles.loc[
            mailles["num_maille"].isin(extra)
        ]
    )

mailles[
    ["num_maille","lambx93","lamby93"]
].head(10)

# ============================================================
# 7. Validate SWI grid coordinates by spatial metadata
# ============================================================

# Keep only SWI grid cells available in the metadata
coords_swi_valid = coords_swi[
    coords_swi["NUMERO"].isin(mailles["num_maille"])
]

test = (
    coords_swi_valid
    .merge(
        mailles,
        left_on=["NUMERO", "LAMBX", "LAMBY"],
        right_on=["num_maille", "lambx93", "lamby93"],
        how="inner"
    )
)

print("Coordinate matching shape:", test.shape)

assert (
    test.shape[0] == coords_swi_valid.shape[0]
), "Some SWI grid cells could not be matched with the grid metadata."

print("All SWI grid cells available in the metadata were successfully matched.")

# ============================================================
# 8. Build SWI grid geometries
# ============================================================

# Half-side length of an 8 km × 8 km grid cell
half = 4000

mailles["geometry"] = mailles.apply(
    lambda r: box(
        r["lambx93"] - half,
        r["lamby93"] - half,
        r["lambx93"] + half,
        r["lamby93"] + half
    ),
    axis=1
)

gdf_mailles = gpd.GeoDataFrame(
    mailles,
    geometry="geometry",
    crs="EPSG:2154"
)

print("Grid CRS:", gdf_mailles.crs)
print("Grid extent:", gdf_mailles.total_bounds)

# ============================================================
# 9. Load municipality boundaries
# ============================================================

communes = gpd.read_file(
    "/content/sample_data/communes_simplified.gpkg"
)

print("Original CRS:", communes.crs)

communes = communes.to_crs(gdf_mailles.crs)

print("Projected CRS:", communes.crs)
print("Number of municipalities:", communes["code_insee"].nunique())
print("Municipality extent:", communes.total_bounds)

display(communes.head())



# ============================================================
# 11. Compute municipality–SWI grid intersections
# ============================================================

intersections = gpd.overlay(
    communes,
    gdf_mailles,
    how="intersection",
    keep_geom_type=True
)

print("Number of municipality-grid intersections:", len(intersections))

# Compute intersection area
intersections["area_intersection"] = intersections.geometry.area

# Compute municipality area
communes_area = communes.copy()

communes_area["area_commune"] = communes_area.geometry.area

communes_area = communes_area[
    ["code_insee", "area_commune"]
]

mapping_swi = intersections.merge(
    communes_area,
    on="code_insee",
    how="left"
)

# Compute area-based weights
mapping_swi["weight"] = (
    mapping_swi["area_intersection"]
    /
    mapping_swi["area_commune"]
)

print("Preview of the weighted mapping:")

display(
    mapping_swi[
        [
            "code_insee",
            "num_maille",
            "area_intersection",
            "area_commune",
            "weight"
        ]
    ].head()
)

# ============================================================
# 12. Validate area-based weights
# ============================================================

weights_sum = (
    mapping_swi
    .groupby("code_insee")["weight"]
    .sum()
)

print("Sum of weights by municipality:")
print(weights_sum.describe())

print()
print("Minimum weight sum:", weights_sum.min())
print("Maximum weight sum:", weights_sum.max())
print("Mean weight sum:", weights_sum.mean())

# ============================================================
# Inspect municipalities with incomplete weight coverage
# ============================================================

weights_problem = weights_sum[
    ~np.isclose(weights_sum, 1, atol=1e-6)
]

print()
print("Number of municipalities with weight sums different from 1:")
print(len(weights_problem))

if len(weights_problem) > 0:

    print("\nMunicipalities with the largest deviations:")

    display(
        weights_problem
        .sort_values()
        .head(20)
    )

    print("\nSummary of weight sum deviations:")

    display(
        (weights_problem - 1).describe()
    )

else:

    print("All municipalities have weight sums equal to 1.")

# ============================================================
# 13. Identify municipalities without SWI coverage
# ============================================================

communes_sans_swi = (
    set(communes["code_insee"])
    -
    set(mapping_swi["code_insee"])
)

print("Number of municipalities without SWI coverage:", len(communes_sans_swi))
print(sorted(communes_sans_swi))

coverage_rate = 100 * (
    1
    -
    len(communes_sans_swi)
    /
    communes["code_insee"].nunique()
)

print("Municipality coverage rate:", coverage_rate, "%")

if len(communes_sans_swi) > 0:
    display(
        communes[
            communes["code_insee"].isin(communes_sans_swi)
        ]
    )

# ============================================================
# 14. Analyze the number of SWI grid cells per municipality
# ============================================================

nb_mailles = (
    mapping_swi
    .groupby("code_insee")["num_maille"]
    .nunique()
)

print("Number of SWI grid cells per municipality:")
print(nb_mailles.describe())

print("Frequency distribution:")
print(nb_mailles.value_counts().sort_index())

nb_mailles.to_csv(
    "/content/diagnostic_number_of_grid_cells_per_municipality.csv"
)

# ============================================================
# 15. Analyze the distribution of area-based weights
# ============================================================

print("Distribution of area-based weights:")
print(mapping_swi["weight"].describe())

mapping_swi["weight"].to_csv(
    "/content/diagnostic_area_weight_distribution.csv",
    index=False
)

import matplotlib.pyplot as plt
import seaborn as sns

# ============================================================
# 16. Plot mapping diagnostics
# ============================================================

# Apply a clean visualization style
sns.set_theme(style="whitegrid")

fig, (ax1, ax2) = plt.subplots(
    1,
    2,
    figsize=(14, 5)
)

# Color palette
color1 = "#4C72B0"
color2 = "#DD8452"

# ------------------------------------------------------------
# SWI grid cells per municipality
# ------------------------------------------------------------

nb_mailles.plot.hist(
    bins=30,
    ax=ax1,
    color=color1,
    edgecolor="white",
    alpha=0.85
)

ax1.set_title(
    "SWI Grid Cells",
    fontsize=11,
    fontweight="bold",
    pad=12
)

ax1.set_xlabel(
    "Grid cells",
    fontsize=10
)

ax1.set_ylabel(
    "Municipalities",
    fontsize=10
)

ax1.tick_params(labelsize=9)

# ------------------------------------------------------------
# Area-based weights
# ------------------------------------------------------------

mapping_swi["weight"].plot.hist(
    bins=30,
    ax=ax2,
    color=color2,
    edgecolor="white",
    alpha=0.85
)

ax2.set_title(
    "Area-Based Weights",
    fontsize=11,
    fontweight="bold",
    pad=12
)

ax2.set_xlabel(
    "Weight",
    fontsize=10
)

ax2.set_ylabel(
    "Intersections",
    fontsize=10
)

ax2.tick_params(labelsize=9)

plt.tight_layout()

plt.savefig(
    "/content/mapping_diagnostics.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

import matplotlib.pyplot as plt
from matplotlib.patches import Patch

# ============================================================
# 17. Plot municipalities excluded from the SWI mapping
# ============================================================

if len(communes_sans_swi) > 0:

    codes = sorted(communes_sans_swi)

    fig, ax = plt.subplots(figsize=(10, 10))

    # Background municipalities
    communes.plot(
        ax=ax,
        facecolor="#F5F5F5",
        edgecolor="#E0E0E0",
        linewidth=0.5
    )

    # SWI grid
    gdf_mailles.boundary.plot(
        ax=ax,
        color="#7F8C8D",
        linewidth=0.3,
        alpha=0.6
    )

    # Municipalities excluded from the SWI mapping
    communes[
        communes["code_insee"].isin(codes)
    ].plot(
        ax=ax,
        facecolor="#E74C3C",
        edgecolor="#C0392B",
        linewidth=1.5,
        alpha=0.8
    )

    ax.set_title(
        "SWI Grid Coverage",
        fontsize=14,
        fontweight="bold",
        pad=15
    )

    legend_elements = [
        Patch(
            facecolor="#E74C3C",
            edgecolor="#C0392B",
            label="Excluded municipalities (n = 5)"
        )
    ]

    ax.legend(
        handles=legend_elements,
        loc="lower left",
        frameon=True,
        fontsize=10
    )

    ax.axis("off")

    plt.tight_layout()

    plt.savefig(
        "/content/swi_grid_coverage.png",
        dpi=300,
        bbox_inches="tight"
    )

    plt.show()

# ============================================================
# 18. Export the final weighted mapping
# ============================================================

mapping_final = mapping_swi[
    [
        "code_insee",
        "num_maille",
        "weight"
    ]
].copy()

print("Preview of the final mapping:")
display(mapping_final.head())

print("Final mapping shape:", mapping_final.shape)

print("Summary statistics:")
display(mapping_final.describe())

print("Weight distribution:")
display(mapping_final["weight"].describe())

mapping_final.to_csv(
    "/content/mapping_SWI_communes_weighted.csv",
    index=False
)

mapping_final.to_parquet(
    "/content/mapping_SWI_communes_weighted.parquet",
    index=False
)

print("Final weighted mapping saved.")

assert mapping_final.duplicated(
    subset=["code_insee", "num_maille"]
).sum() == 0, (
    "Duplicate municipality-grid pairs found in the final mapping."
)

print("No duplicate municipality-grid pairs found.")

# ============================================================
# 19. Export mapping summary
# ============================================================

summary = {
    "n_swi_rows": len(swi),
    "n_swi_grid_cells": swi["NUMERO"].nunique(),
    "date_min": swi["DATE"].min(),
    "date_max": swi["DATE"].max(),
    "n_municipalities": communes["code_insee"].nunique(),
    "n_municipalities_covered": mapping_final["code_insee"].nunique(),
    "n_municipalities_without_swi": len(communes_sans_swi),
    "coverage_rate_percent": coverage_rate,
    "mean_grid_cells_per_municipality": nb_mailles.mean(),
    "median_grid_cells_per_municipality": nb_mailles.median(),
    "max_grid_cells_per_municipality": nb_mailles.max(),
    "min_weight": mapping_final["weight"].min(),
    "max_weight": mapping_final["weight"].max(),
    "mean_weight": mapping_final["weight"].mean()
}

summary_df = pd.DataFrame(
    list(summary.items()),
    columns=["indicator", "value"]
)

display(summary_df)

summary_df.to_csv(
    "/content/swi_mapping_summary.csv",
    index=False
)

print("Mapping summary saved.")

print(communes_map["class"].value_counts())
print(communes_map["class"].cat.categories)

# ==========================================================
# 20. Dominant SWI grid-cell contribution map
# ==========================================================

import matplotlib.pyplot as plt

# ----------------------------------------------------------
# Compute dominant surface weight
# ----------------------------------------------------------

dominant = (
    mapping_final
    .groupby("code_insee")["weight"]
    .max()
    .rename("dominant_weight")
)

communes_map = communes.copy()

communes_map = communes_map.merge(
    dominant,
    on="code_insee",
    how="left"
)

# ----------------------------------------------------------
# Quantile classification (4 classes)
# ----------------------------------------------------------

communes_map["class"] = pd.qcut(
    communes_map["dominant_weight"],
    q=4,
    duplicates="drop"
)

# Quantile limits
q = (
    communes_map["dominant_weight"]
    .quantile([0, .25, .50, .75, 1])
    .round(2)
)

labels = [
    f"{q.iloc[i]:.2f} – {q.iloc[i+1]:.2f}"
    for i in range(len(q)-1)
]

# ----------------------------------------------------------
# Figure style
# ----------------------------------------------------------

plt.rcParams.update({
    "font.family": "serif",
    "font.serif": [
        "Times New Roman",
        "DejaVu Serif"
    ]
})

fig, ax = plt.subplots(
    figsize=(8.2, 9.3),
    dpi=600
)

# ----------------------------------------------------------
# Map
# ----------------------------------------------------------

communes_map.plot(
    column="class",
    cmap="RdBu_r",
    categorical=True,
    linewidth=0,
    edgecolor="none",
    legend=True,
    legend_kwds={
        "title": "Dominant weight",
        "loc": "lower left",
        "frameon": False,
        "fontsize": 10,
        "title_fontsize": 11
    },
    ax=ax
)

# ----------------------------------------------------------
# France outline
# ----------------------------------------------------------

communes_map.dissolve().boundary.plot(
    ax=ax,
    color="#4D4D4D",
    linewidth=0.45
)

# ----------------------------------------------------------
# Replace legend labels
# ----------------------------------------------------------

leg = ax.get_legend()

for txt, label in zip(leg.get_texts(), labels):
    txt.set_text(label)

# ----------------------------------------------------------
# No title (handled in LaTeX)
# ----------------------------------------------------------

ax.set_axis_off()

# ----------------------------------------------------------
# Export
# ----------------------------------------------------------

plt.tight_layout()

plt.savefig(
    "/content/Figure_DominantWeight_SWI.png",
    dpi=600,
    bbox_inches="tight",
    facecolor="white"
)

plt.show()